# Generated by Django 2.1.5 on 2019-02-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPlayerList',
            fields=[
                ('game_id', models.CharField(db_column='game_id', max_length=13, primary_key=True, serialize=False)),
                ('gday', models.CharField(db_column='gday', max_length=8)),
                ('pos', models.CharField(db_column='pos', max_length=1)),
                ('pcode', models.CharField(db_column='pcode', max_length=5)),
                ('tb', models.CharField(blank=True, db_column='tb', max_length=1, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=30, null=True)),
                ('top_point', models.IntegerField(blank=True, db_column='top_point', null=True)),
            ],
            options={
                'db_table': 'top_players',
                'managed': False,
            },
        ),
    ]
